#define __BRM_VERSION_MAJOR__ 0
#define __BRM_VERSION_MINOR__ 7
#define __BRM_VERSION_PATCH__ 6
#define __BRM_VERSION_BUILD__ 1

#define __BRM_VERSION__ __BRM_VERSION_MAJOR__##.##__BRM_VERSION_MINOR__##.##__BRM_VERSION_PATCH__##.##__BRM_VERSION_BUILD__
#define __BRM_VERSION_STR__ #__BRM_VERSION__
